version: "3.8"
services:
  app:
    build:
      context: .
    volumes:
      - .:/covid-map
    ports:
      - 3000:3000
    image: covid-map:react
    container_name: react_container
    command: npm start